name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd fe
        npm install
        npx jest
        if [ $? = 0 ]; then
          BOT_MESSAGE="<!here>\nGitHubのジョブは無事に成功したようです。\nお疲れ様でした。"
          STATUS=0
        else
          BOT_MESSAGE="<!here>\nGitHubのジョブが失敗したようです。お手隙の際に確認してくださいね。\nhttps://github.com/Kanta0111/MuteRemider/actions"
          STATUS=1
        fi

        curl -X POST --data-urlencode "payload={\"channel\": \"#development\", \"text\": \"${BOT_MESSAGE}\"}" https://hooks.slack.com/services/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
        exit $STATUS
      env:
        CI: true
